"""Pydantic v2 -> TypeScript interfaces.

Source of truth: vena_lite.schemas. Output: add-in/src/types/generated.ts.

Requires `json-schema-to-typescript` on PATH (provides the `json2ts` CLI).
Install once: `npm install -g json-schema-to-typescript`.

Determinism: writes a header banner, normalizes line endings to LF, ensures a
trailing newline. CI's drift check diffs the regenerated file against what's
committed; either side drifting (tooling update, schema change without regen)
fails the gate.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

# Make `json2ts.cmd` discoverable on Windows when global npm bin isn't on PATH.
_npm_global = Path(os.environ.get("APPDATA", "")) / "npm"
if _npm_global.is_dir():
    os.environ["PATH"] = f"{_npm_global};{os.environ.get('PATH', '')}"

_BANNER = (
    "/* AUTO-GENERATED by backend/scripts/generate_ts_types.py — do not edit. */\n"
    "/* Source of truth: vena_lite.schemas (Pydantic v2). Regenerate via `make types`. */\n\n"
)


def _resolve_json2ts() -> str:
    for name in ("json2ts.cmd", "json2ts"):
        path = shutil.which(name)
        if path:
            return path
    print(
        "error: `json2ts` not found on PATH.\n"
        "Install with: npm install -g json-schema-to-typescript",
        file=sys.stderr,
    )
    sys.exit(2)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    output = repo_root / "add-in" / "src" / "types" / "generated.ts"
    output.parent.mkdir(parents=True, exist_ok=True)

    json2ts_cmd = _resolve_json2ts()

    # Defer import so a missing dep produces a usable error message at run time
    # rather than at module-load time.
    from pydantic2ts import generate_typescript_defs

    # Generate into a tmp file first; we post-process before placing.
    tmp_output = output.with_suffix(".ts.tmp")
    generate_typescript_defs(
        "vena_lite.schemas",
        str(tmp_output),
        json2ts_cmd=json2ts_cmd,
    )

    body = tmp_output.read_text(encoding="utf-8")
    tmp_output.unlink()

    # Force LF; strip BOM if present.
    body = body.replace("\r\n", "\n").lstrip("﻿")
    if not body.endswith("\n"):
        body += "\n"

    final = _BANNER + body
    output.write_text(final, encoding="utf-8", newline="\n")
    print(f"wrote {output} ({len(final)} bytes)")

    # Optional: invoke from the script itself rather than via subprocess for
    # callers that want a return code without importing.
    return 0


if __name__ == "__main__":
    sys.exit(main())
