/* AUTO-GENERATED by backend/scripts/generate_ts_types.py — do not edit. */
/* Source of truth: vena_lite.schemas (Pydantic v2). Regenerate via `make types`. */

/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

export interface CellValidationError {
  cell_index: number;
  invalid_members: InvalidMember[];
}
export interface InvalidMember {
  dim: string;
  member: string;
  reason?: string | null;
}
export interface CreatedDimMember {
  dim: string;
  member: string;
}
/**
 * Filter on one dimension. `members=None` means 'all members of this dim'.
 */
export interface DimFilter {
  members?: string[] | null;
}
export interface DimMemberCreateRequest {
  request_id: string;
  id: string;
  display_name?: string | null;
  parent?: string | null;
  ordinal?: number;
  rollup_op?: string;
}
export interface DimMemberDeleteResponse {
  request_id: string;
  dim: "account" | "entity" | "costcenter" | "period" | "scenario" | "version";
  member: string;
  descendants_deleted: string[];
  audit_id: number;
}
/**
 * One row in `GET /dimensions/{dim}/members`.
 *
 * Slice 9: `display_name` is the user-facing alias. NULL → render falls back
 * to `id`. Cube facts and driver formulas always reference `id` (immutable).
 */
export interface DimMemberInfo {
  id: string;
  is_leaf: boolean;
  parent?: string | null;
  rollup_op?: string;
  display_name?: string | null;
}
export interface DimMemberMutationResponse {
  request_id: string;
  dim: "account" | "entity" | "costcenter" | "period" | "scenario" | "version";
  member: DimMemberInfo;
  audit_id: number;
}
/**
 * PATCH body. Omitted fields stay unchanged. `display_name=null` clears
 * the alias (renders as id again). No `id` (immutable). No `parent` (no
 * reparent in v1).
 */
export interface DimMemberUpdateRequest {
  request_id: string;
  display_name?: string | null;
  ordinal?: number | null;
}
export interface DimMembersResponse {
  dim: string;
  members: DimMemberInfo[];
}
export interface DriverDefineRequest {
  request_id: string;
  account: string;
  formula: string;
}
export interface DriverDefineResponse {
  request_id: string;
  account: string;
  formula: string;
  references: string[];
  initial_computed_count: number;
}
export interface DriverDeleteResponse {
  request_id: string;
  account: string;
  formula: string;
  audit_id: number;
}
export interface DriverInfo {
  account: string;
  formula: string;
}
export interface DriverListResponse {
  drivers: DriverInfo[];
}
export interface FactRow {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
  value: string;
}
export interface OverrideIntersection {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
}
export interface OverrideReleaseRequest {
  request_id: string;
  /**
   * @minItems 1
   */
  cells: [OverrideIntersection, ...OverrideIntersection[]];
}
export interface OverrideRequest {
  request_id: string;
  /**
   * @minItems 1
   */
  cells: [SubmittedCell, ...SubmittedCell[]];
}
export interface SubmittedCell {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
  value: string;
}
export interface OverrideResponse {
  request_id: string;
  accepted_count: number;
}
export interface ScenarioCopyRequest {
  request_id: string;
  source: ScenarioRef;
  target: ScenarioRef;
}
export interface ScenarioRef {
  scenario: string;
  version: string;
}
export interface ScenarioCopyResponse {
  request_id: string;
  source: ScenarioRef;
  target: ScenarioRef;
  copied_count: number;
  created_members: CreatedDimMember[];
}
export interface SliceRequest {
  filters?: {
    [k: string]: DimFilter;
  };
}
export interface SliceResponse {
  rows: FactRow[];
  total: number;
}
export interface SubmitRequest {
  request_id: string;
  /**
   * @minItems 1
   */
  cells: [SubmittedCell, ...SubmittedCell[]];
}
export interface SubmitResponse {
  request_id: string;
  accepted_count: number;
}
export interface ValueResponse {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
  value: string;
  source: string;
  loaded_at: string;
}
