/* AUTO-GENERATED by backend/scripts/generate_ts_types.py — do not edit. */
/* Source of truth: vena_lite.schemas (Pydantic v2). Regenerate via `make types`. */

/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

export interface CellValidationError {
  cell_index: number;
  invalid_members: InvalidMember[];
}
export interface InvalidMember {
  dim: string;
  member: string;
  reason?: string | null;
}
export interface CreatedDimMember {
  dim: string;
  member: string;
}
/**
 * Filter on one dimension. `members=None` means 'all members of this dim'.
 */
export interface DimFilter {
  members?: string[] | null;
}
/**
 * One row in `GET /dimensions/{dim}/members`.
 */
export interface DimMemberInfo {
  id: string;
  is_leaf: boolean;
  parent?: string | null;
  rollup_op?: string;
}
export interface DimMembersResponse {
  dim: string;
  members: DimMemberInfo[];
}
export interface DriverDefineRequest {
  request_id: string;
  account: string;
  formula: string;
}
export interface DriverDefineResponse {
  request_id: string;
  account: string;
  formula: string;
  references: string[];
  initial_computed_count: number;
}
export interface DriverInfo {
  account: string;
  formula: string;
}
export interface DriverListResponse {
  drivers: DriverInfo[];
}
export interface FactRow {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
  value: string;
}
export interface ScenarioCopyRequest {
  request_id: string;
  source: ScenarioRef;
  target: ScenarioRef;
}
export interface ScenarioRef {
  scenario: string;
  version: string;
}
export interface ScenarioCopyResponse {
  request_id: string;
  source: ScenarioRef;
  target: ScenarioRef;
  copied_count: number;
  created_members: CreatedDimMember[];
}
export interface SliceRequest {
  filters?: {
    [k: string]: DimFilter;
  };
}
export interface SliceResponse {
  rows: FactRow[];
  total: number;
}
export interface SubmitRequest {
  request_id: string;
  /**
   * @minItems 1
   */
  cells: [SubmittedCell, ...SubmittedCell[]];
}
export interface SubmittedCell {
  account: string;
  entity: string;
  costcenter: string;
  period: string;
  scenario: string;
  version: string;
  value: string;
}
export interface SubmitResponse {
  request_id: string;
  accepted_count: number;
}
